# Generated by Django 5.2.1 on 2025-05-16 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=35)),
                ('price', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('stock', models.PositiveIntegerField(default=1)),
                ('images', models.ImageField(upload_to='')),
                ('Categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='shop.category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
